#!/bin/bash

cd `dirname $0`

# Creates .gz files for resource server
#
# Checks for %INCLUDE{}% and %Var123% and will not compress such files.
# (The server may compress the resulting data stream.)

FILES="$*"
if [ -z "$FILES" ]; then FILES="*.js *.css" ; fi

for FILE in $FILES; do
   rm -f $FILE.gz
   if ! grep -qP '(%INCLUDE\{.*?\}%|%[A-Za-z][\w]*%)' $FILE ; then
       cp -p $FILE $FILE.ungz
       gzip $FILE
       mv $FILE.ungz $FILE
       ls -l $FILE{,.gz}
   fi
done
