FOSWIKI_ROOT?=~/foswiki/core
TARGET=\
	foswikiArray.js \
	foswikiCSS.js \
	foswikiDate.js \
	foswiki_edit.js \
	foswikiEvent.js \
	foswikiForm.js \
	foswikiHTML.js \
	foswikilib.js \
	foswikiPref.js \
	foswiki_renamebase.js \
	foswikiString.js \
	foswikiStringUnicodeChars.js \
	foswikiStyles.js \
	foswikiWebTopicCreator.js \
	foswikiWindow.js 

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

clean:
	rm -f $(TARGET) *.gz

