FOSWIKI_ROOT?=~/foswiki/core
TARGET=\
	colors.css \
	column_left.css \
	column_left_flex.css \
	column_none.css \
	column_right.css \
	column_right_flex.css \
	layout.css \
	style.css \
	variant_foswiki_frame.css \
	variant_foswiki_noframe.css 

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

clean:
	rm -f $(TARGET) *.gz
