FOSWIKI_ROOT?=~/foswiki/core
TARGET= configure.js resig.js types.js reset.css configure.css render_tml.js

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

clean:
	rm $(TARGET) *.gz
