#!/usr/bin/perl
# See bottom of file for license and copyright information

use strict;
use warnings;

use LWP::Simple;

# COMMIT-MSG CLIENT HOOK for Foswiki git
#
# The commit-msg hook tests that the message identifies one or more
# tasks, and that each task is in a state to accept checkins.
#
# STDERR ends up on the users' terminal

my $failmsg = '';
my $logmsg;

{
    local $/ = undef;
    open my $fh, "<", $ARGV[0]
      or die "could not open $ARGV[0]: $!";
    $logmsg = <$fh>;
    close $fh;
};

fail("No Bug item in log message\n") unless ( $logmsg =~ /^Item\d+\s*:/ );

my @items;
$logmsg =~ s/\b(Item\d+)\s*:/push(@items, $1); '';/gem;
foreach my $item (@items) {
    my $url   = "http://foswiki.org/Tasks/ItemStatusQuery?item=$item;skin=text";
    my $state = get $url;

    unless ( defined $state ) {
        $failmsg .=
"ERROR: GET on Tasks.ItemStatusQuery failed.  Check http://foswiki.org/Tasks/ItemStatusQuery\n";
        fail($failmsg);
    }

    $failmsg .= "$item does not exist\n" unless $state;

    if ( $state =~
        /^(Waiting for Release|Closed|No Action Required|Proposal Required)$/ )
    {
        $failmsg .= "$item is in $state state; cannot check in\n";
    }

}

fail($failmsg) if $failmsg;

exit 0;

# PLEASE keep this message in sync with
# http://foswiki.org/Development/SvnRepository#RulesForCheckins
sub fail {
    my $message = shift;
    print STDERR <<"EOF";
--------------------------------------------------------------
Illegal Foswiki commit:

=====
$message=====

http://foswiki.org/Development/SvnRepository#RulesForCheckins
Rules - checkins must:
1. Have a comment...
2. ...with relevant ItemNNN topics in the first line, example:

Item12345: Item12346: fixed foo, updated release notes

3. Use ItemNNN topics which are open at the time of checkin,
   I.E. *not* one of: Closed, Waiting For Release, No Action
   or Proposal Required
4. Have "tidied" source code if the TIDY control file in the
   root of the extension calls for it, see:
   http://foswiki.org/Development/TIDY

NB Getting rejected commits with perltidy? We are checking
   using version ##FIXME: Perl::Tidy::VERSION
   See http://foswiki.org/Development/PerlTidy#Versions

------------TRUNCATED COMMIT MESSAGE FOLLOWS------------------------
EOF
    $logmsg =~ s/^# Untracked files:.*//ms;
    print STDERR $logmsg;
    exit 1;
}

__END__
Foswiki - The Free and Open Source Wiki, http://foswiki.org/

Copyright (C) 2014 Foswiki Contributors. Foswiki Contributors
are listed in the AUTHORS file in the root of this distribution.
NOTE: Please extend that file, not this notice.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version. For
more details read LICENSE in the root of this distribution.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

As per the GPL, removal of this notice is prohibited.

