TARGET= \
  jquery.superfish.js \
  jquery.superfish.css \
  jquery.superfish-navbar.css \
  jquery.superfish-vertical.css \
  $(JQUERYPLUGIN_LIB)/SUPERFISH.pm \
  $(JQUERYPLUGIN_LIB)/SUPERFISH.pm

-include ../../Makefile.include
