# ---+ Extensions
# ---++ UpdatesPlugin
# This is the configuration used by the <b>UpdatesPlugin</b>.

# **URL**
# The source URL where to get the latest version of extensions. The URL must point to a page
# that generates a list in the same format as the list generated by
# http://foswiki.org/Extensions/UpdatesPluginReport
$Foswiki::cfg{Plugins}{UpdatesPlugin}{ReportUrl} = "https://foswiki.org/Extensions/UpdatesPluginReport";

# **NUMBER**
# Number of seconds to cache the update report for extensions. Default is 24 hours.
$Foswiki::cfg{Plugins}{UpdatesPlugin}{CacheTimeout} = 86400;

# **STRING**
# A list of extensions that shall not be checked for updates on foswiki.org. This setting can be used
# to prevent plugins not hosted on foswiki.org from being reported to the outside world.
$Foswiki::cfg{Plugins}{UpdatesPlugin}{ExcludeExtensions} = '';

# **URLPATH CHECK='emptyok'**
# The URL of the 'configure' program used to install extensions on your Foswiki. If not configured,
# it uses the default configure script URL.
$Foswiki::cfg{Plugins}{UpdatesPlugin}{ConfigureUrl} = '';

1;
