SUBDIRS=\
  base \
  black-tie \
  blitzer \
  cupertino \
  dark-hive \
  dot-luv \
  eggplant \
  excite-bike \
  flick \
  foswiki \
  foswiki-fontawesome \
  hot-sneaks \
  humanity \
  le-frog \
  mint-choc \
  overcast \
  pepper-grinder \
  redmond \
  smoothness \
  south-street \
  start \
  sunny \
  swanky-purse \
  trontastic \
  ui-darkness \
  ui-lightness \
  vader 

all: $(SUBDIRS)

-include ../../../Makefile.include
