SUBDIRS=\
  autocomplete \
  bgiframe \
  blockui \
  button \
  chili \
  cookie \
  corner \
  cycle \
  debug \
  easing \
  farbtastic \
  fluidfont \
  focus \
  form \
  foswiki \
  fullcalendar \
  gradient \
  grid \
  hoverintent \
  ifixpng \
  innerfade \
  localscroll \
  maskedinput \
  media \
  metadata \
  nifty \
  rating \
  scrollto \
  serialscroll \
  shake \
  shrinkurls \
  simplemodal \
  slimbox \
  spinner \
  superfish \
  supersubs \
  tabpane \
  textboxlist \
  toggle \
  tooltip \
  treeview \
  validate \
  wikiword 

all: $(SUBDIRS)

-include ../Makefile.include
