SUBDIRS=\
  cookie \
  autocomplete \
  bgiframe \
  blockUI \
  button \
  chilli \
  cookie \
  cycle \
  debug \
  easing \
  empty \
  form \
  foswiki \
  hoverIntent \
  ifixpng \
  innerfade \
  maskedinput \
  media \
  metadata \
  nifty \
  rating \
  shake \
  shrinkurls \
  simplemodal \
  spinner \
  superfish \
  tabpane \
  tooltip \
  treeview \
  validate \
  wikiword \

all: $(SUBDIRS)

-include ../Makefile.include
