(function($){$.fn.tabpane=function(options){$.log("called tabpane()");if(typeof(options)=='undefined'){options={};}
var opts=$.extend({},$.fn.tabpane.defaults,options);return this.each(function(){var $thisPane=$(this);var thisOpts=$.extend({},opts,$thisPane.metadata());var $tabContainer=$thisPane;var $tabGroup=$('<ul class="jqTabGroup"></ul>').prependTo($thisPane);var index=1;var currentTabId;$thisPane.children(".jqTab").each(function(){var title=$('h2',this).eq(0).remove().text();$tabGroup.append('<li'+((index==thisOpts.select||this.id==thisOpts.select)?' class="current"':'')+'><a href="javascript:void(0)" data="'+this.id+'">'+title+'</a></li>');if(index==thisOpts.select||this.id==thisOpts.select){currentTabId=this.id;$(this).addClass("current");}else{$.log("hiding "+this.id);$(this).removeClass("current");}
index++;});if(currentTabId){switchTab(currentTabId,currentTabId,thisOpts);}
if(thisOpts.autoMaxExpand){window.setTimeout(autoMaxExpand,100);}
$(".jqTabGroup li > a",this).click(function(){$(this).blur();var newTabId=$(this).attr('data');if(newTabId!=currentTabId){$("#"+currentTabId).removeClass("current");$("#"+newTabId).addClass("current");$(this).parent().parent().children("li").removeClass("current");$(this).parent().addClass("current");switchTab(currentTabId,newTabId,thisOpts);currentTabId=newTabId;}
return false;});});};function switchTab(oldTabId,newTabId,thisOpts){jQuery.log("switch from "+oldTabId+" to "+newTabId);var $newTab=jQuery("#"+newTabId);if(!thisOpts[newTabId]){thisOpts[newTabId]=$newTab.metadata();}
var data=thisOpts[newTabId];if(typeof(data.beforeHandler)!="undefined"){var command="{ oldTab = '"+oldTabId+"'; newTab = '"+newTabId+"'; "+data.beforeHandler+";}";jQuery.log("exec "+command);var func=new Function(command);func();}
if(typeof(data.url)!="undefined"){var container=data.container||'.jqTabContents';var $container=$newTab.find(container);jQuery.log("loading "+data.url+" into "+container);if(typeof(data.afterLoadHandler)!="undefined"){var command="{ oldTab = '"+oldTabId+"'; newTab = '"+newTabId+"'; "+data.afterLoadHandler+";}";jQuery.log("after load handler "+command);var func=new Function(command);$container.load(data.url,undefined,func);}else{$container.load(data.url);}
delete thisOpts[newTabId].url;}
if(typeof(data.afterHandler)!="undefined"){var command="{ oldTab = '"+oldTabId+"'; newTab = '"+newTabId+"'; "+data.afterHandler+";}";jQuery.log("exec "+command);var func=new Function(command);func();}}
$.fn.tabpane.defaults={select:1};})(jQuery);function autoMaxExpand(){fixHeightOfPane();window.setTimeout(function(){jQuery(window).one("resize",function(){autoMaxExpand()});},100);}
var bottomBarHeight=-1;function fixHeightOfPane(){var selector=(typeof(newTab)!='undefined')?"#"+newTab:".jqTab:visible";selector+=" .jqTabContents";var $container=jQuery(selector);var paneOffset=$container.offset({scroll:false,border:true,padding:true,margin:true});if(typeof(paneOffset)!='undefined'){var paneTop=paneOffset.top;if(bottomBarHeight<0){bottomBarHeight=jQuery('.natEditBottomBar').outerHeight({margin:true});}
var windowHeight=jQuery(window).height();if(!windowHeight){windowHeight=window.innerHeight;}
var height=windowHeight-paneTop-bottomBarHeight-50;var newTabSelector;if(typeof(newTab)=='undefined'){newTabSelector=".jqTab:visible";}else{newTabSelector="#"+newTab;}
jQuery(newTabSelector+" .jqTabContents").filter(function(index){return jQuery(".natEditAutoMaxExpand",this).length==0;}).each(function(){jQuery(this).height(height);});}};
