(function(){var each=tinymce.each,entities=null,defs={paste_auto_cleanup_on_paste:true,paste_block_drop:false,paste_retain_style_properties:"none",paste_strip_class_attributes:"mso",paste_remove_spans:false,paste_remove_styles:false,paste_remove_styles_if_webkit:true,paste_convert_middot_lists:true,paste_convert_headers_to_strong:false,paste_dialog_width:"450",paste_dialog_height:"400",paste_text_use_dialog:false,paste_text_sticky:false,paste_text_notifyalways:false,paste_text_linebreaktype:"p",paste_text_replacements:[[/\u2026/g,"..."],[/[\x93\x94\u201c\u201d]/g,'"'],[/[\x60\x91\x92\u2018\u2019]/g,"'"]]};function getParam(ed,name){return ed.getParam(name,defs[name]);}
tinymce.create('tinymce.plugins.PastePlugin',{init:function(ed,url){var t=this;t.editor=ed;t.url=url;t.onPreProcess=new tinymce.util.Dispatcher(t);t.onPostProcess=new tinymce.util.Dispatcher(t);t.onPreProcess.add(t._preProcess);t.onPostProcess.add(t._postProcess);t.onPreProcess.add(function(pl,o){ed.execCallback('paste_preprocess',pl,o);});t.onPostProcess.add(function(pl,o){ed.execCallback('paste_postprocess',pl,o);});ed.pasteAsPlainText=false;function process(o,force_rich){var dom=ed.dom;t.onPreProcess.dispatch(t,o);o.node=dom.create('div',0,o.content);t.onPostProcess.dispatch(t,o);o.content=ed.serializer.serialize(o.node,{getInner:1});if((!force_rich)&&(ed.pasteAsPlainText)){t._insertPlainText(ed,dom,o.content);if(!getParam(ed,"paste_text_sticky")){ed.pasteAsPlainText=false;ed.controlManager.setActive("pastetext",false);}}else if(/<(p|h[1-6]|ul|ol)/.test(o.content)){t._insertBlockContent(ed,dom,o.content);}else{t._insert(o.content);}}
ed.addCommand('mceInsertClipboardContent',function(u,o){process(o,true);});if(!getParam(ed,"paste_text_use_dialog")){ed.addCommand('mcePasteText',function(u,v){var cookie=tinymce.util.Cookie;ed.pasteAsPlainText=!ed.pasteAsPlainText;ed.controlManager.setActive('pastetext',ed.pasteAsPlainText);if((ed.pasteAsPlainText)&&(!cookie.get("tinymcePasteText"))){if(getParam(ed,"paste_text_sticky")){ed.windowManager.alert("Paste is now in plain text mode. Click again to toggle back to regular paste mode. After you paste something you will be returned to regular paste mode.");}else{ed.windowManager.alert("Paste is now in plain text mode. Click again to toggle back to regular paste mode.");}
if(!getParam(ed,"paste_text_notifyalways")){cookie.set("tinymcePasteText","1",new Date(new Date().getFullYear()+1,12,31))}}});}
ed.addButton('pastetext',{title:'paste.paste_text_desc',cmd:'mcePasteText'});ed.addButton('selectall',{title:'paste.selectall_desc',cmd:'selectall'});function grabContent(e){var n,or,rng,sel=ed.selection,dom=ed.dom,body=ed.getBody(),posY;if(dom.get('_mcePaste'))
return;n=dom.add(body,'div',{id:'_mcePaste','class':'mcePaste'},'\uFEFF');if(body!=ed.getDoc().body)
posY=dom.getPos(ed.selection.getStart(),body).y;else
posY=body.scrollTop;dom.setStyles(n,{position:'absolute',left:-10000,top:posY,width:1,height:1,overflow:'hidden'});if(tinymce.isIE){rng=dom.doc.body.createTextRange();rng.moveToElementText(n);rng.execCommand('Paste');dom.remove(n);if(n.innerHTML==='\uFEFF'){ed.execCommand('mcePasteWord');e.preventDefault();return;}
process({content:n.innerHTML});return tinymce.dom.Event.cancel(e);}else{function block(e){e.preventDefault();};dom.bind(ed.getDoc(),'mousedown',block);dom.bind(ed.getDoc(),'keydown',block);or=ed.selection.getRng();n=n.firstChild;rng=ed.getDoc().createRange();rng.setStart(n,0);rng.setEnd(n,1);sel.setRng(rng);window.setTimeout(function(){var h='',nl=dom.select('div.mcePaste');each(nl,function(n){each(dom.select('div.mcePaste',n),function(n){dom.remove(n,1);});h+=(dom.select('> span.Apple-style-span div',n)[0]||dom.select('> span.Apple-style-span',n)[0]||n).innerHTML;});each(nl,function(n){dom.remove(n);});if(or)
sel.setRng(or);process({content:h});dom.unbind(ed.getDoc(),'mousedown',block);dom.unbind(ed.getDoc(),'keydown',block);},0);}}
if(getParam(ed,"paste_auto_cleanup_on_paste")){if(tinymce.isOpera||/Firefox\/2/.test(navigator.userAgent)){ed.onKeyDown.add(function(ed,e){if(((tinymce.isMac?e.metaKey:e.ctrlKey)&&e.keyCode==86)||(e.shiftKey&&e.keyCode==45))
grabContent(e);});}else{ed.onPaste.addToTop(function(ed,e){return grabContent(e);});}}
if(getParam(ed,"paste_block_drop")){ed.onInit.add(function(){ed.dom.bind(ed.getBody(),['dragend','dragover','draggesture','dragdrop','drop','drag'],function(e){e.preventDefault();e.stopPropagation();return false;});});}
t._legacySupport();},getInfo:function(){return{longname:'Paste text/word',author:'Moxiecode Systems AB',authorurl:'http://tinymce.moxiecode.com',infourl:'http://wiki.moxiecode.com/index.php/TinyMCE:Plugins/paste',version:tinymce.majorVersion+"."+tinymce.minorVersion};},_preProcess:function(pl,o){var ed=this.editor,h=o.content,grep=tinymce.grep,explode=tinymce.explode,trim=tinymce.trim,len,stripClass;function process(items){each(items,function(v){if(v.constructor==RegExp)
h=h.replace(v,'');else
h=h.replace(v[0],v[1]);});}
if(/class="?Mso|style="[^"]*\bmso-|w:WordDocument/i.test(h)||o.wordContent){o.wordContent=true;process([/^\s*(&nbsp;)+/gi,/(&nbsp;|<br[^>]*>)+\s*$/gi]);if(getParam(ed,"paste_convert_headers_to_strong")){h=h.replace(/<p [^>]*class="?MsoHeading"?[^>]*>(.*?)<\/p>/gi,"<p><strong>$1</strong></p>");}
if(getParam(ed,"paste_convert_middot_lists")){process([[/<!--\[if !supportLists\]-->/gi,'$&__MCE_ITEM__'],[/(<span[^>]+(?:mso-list:|:\s*symbol)[^>]+>)/gi,'$1__MCE_ITEM__']]);}
process([/<!--[\s\S]+?-->/gi,/<(!|script[^>]*>.*?<\/script(?=[>\s])|\/?(\?xml(:\w+)?|img|meta|link|style|\w:\w+)(?=[\s\/>]))[^>]*>/gi,[/<(\/?)s>/gi,"<$1strike>"],[/&nbsp;/gi,"\u00a0"]]);do{len=h.length;h=h.replace(/(<[a-z][^>]*\s)(?:id|name|language|type|on\w+|\w+:\w+)=(?:"[^"]*"|\w+)\s?/gi,"$1");}while(len!=h.length);if(getParam(ed,"paste_retain_style_properties").replace(/^none$/i,"").length==0){h=h.replace(/<\/?span[^>]*>/gi,"");}else{process([[/<span\s+style\s*=\s*"\s*mso-spacerun\s*:\s*yes\s*;?\s*"\s*>([\s\u00a0]*)<\/span>/gi,function(str,spaces){return(spaces.length>0)?spaces.replace(/./," ").slice(Math.floor(spaces.length/2)).split("").join("\u00a0"):"";}],[/(<[a-z][^>]*)\sstyle="([^"]*)"/gi,function(str,tag,style){var n=[],i=0,s=explode(trim(style).replace(/&quot;/gi,"'"),";");each(s,function(v){var name,value,parts=explode(v,":");function ensureUnits(v){return v+((v!=="0")&&(/\d$/.test(v)))?"px":"";}
if(parts.length==2){name=parts[0].toLowerCase();value=parts[1].toLowerCase();switch(name){case"mso-padding-alt":case"mso-padding-top-alt":case"mso-padding-right-alt":case"mso-padding-bottom-alt":case"mso-padding-left-alt":case"mso-margin-alt":case"mso-margin-top-alt":case"mso-margin-right-alt":case"mso-margin-bottom-alt":case"mso-margin-left-alt":case"mso-table-layout-alt":case"mso-height":case"mso-width":case"mso-vertical-align-alt":n[i++]=name.replace(/^mso-|-alt$/g,"")+":"+ensureUnits(value);return;case"horiz-align":n[i++]="text-align:"+value;return;case"vert-align":n[i++]="vertical-align:"+value;return;case"font-color":case"mso-foreground":n[i++]="color:"+value;return;case"mso-background":case"mso-highlight":n[i++]="background:"+value;return;case"mso-default-height":n[i++]="min-height:"+ensureUnits(value);return;case"mso-default-width":n[i++]="min-width:"+ensureUnits(value);return;case"mso-padding-between-alt":n[i++]="border-collapse:separate;border-spacing:"+ensureUnits(value);return;case"text-line-through":if((value=="single")||(value=="double")){n[i++]="text-decoration:line-through";}
return;case"mso-zero-height":if(value=="yes"){n[i++]="display:none";}
return;}
if(/^(mso|column|font-emph|lang|layout|line-break|list-image|nav|panose|punct|row|ruby|sep|size|src|tab-|table-border|text-(?!align|decor|indent|trans)|top-bar|version|vnd|word-break)/.test(name)){return;}
n[i++]=name+":"+parts[1];}});if(i>0){return tag+' style="'+n.join(';')+'"';}else{return tag;}}]]);}}
if(getParam(ed,"paste_convert_headers_to_strong")){process([[/<h[1-6][^>]*>/gi,"<p><strong>"],[/<\/h[1-6][^>]*>/gi,"</strong></p>"]]);}
stripClass=getParam(ed,"paste_strip_class_attributes");if(stripClass!=="none"){function removeClasses(match,g1){if(stripClass==="all")
return'';var cls=grep(explode(g1.replace(/^(["'])(.*)\1$/,"$2")," "),function(v){return(/^(?!mso)/i.test(v));});return cls.length?' class="'+cls.join(" ")+'"':'';};h=h.replace(/ class="([^"]+)"/gi,removeClasses);h=h.replace(/ class=(\w+)/gi,removeClasses);}
if(getParam(ed,"paste_remove_spans")){h=h.replace(/<\/?span[^>]*>/gi,"");}
o.content=h;},_postProcess:function(pl,o){var t=this,ed=t.editor,dom=ed.dom,styleProps;if(o.wordContent){each(dom.select('a',o.node),function(a){if(!a.href||a.href.indexOf('#_Toc')!=-1)
dom.remove(a,1);});if(getParam(ed,"paste_convert_middot_lists")){t._convertLists(pl,o);}
styleProps=getParam(ed,"paste_retain_style_properties");if((tinymce.is(styleProps,"string"))&&(styleProps!=="all")&&(styleProps!=="*")){styleProps=tinymce.explode(styleProps.replace(/^none$/i,""));each(dom.select('*',o.node),function(el){var newStyle={},npc=0,i,sp,sv;if(styleProps){for(i=0;i<styleProps.length;i++){sp=styleProps[i];sv=dom.getStyle(el,sp);if(sv){newStyle[sp]=sv;npc++;}}}
dom.setAttrib(el,'style','');if(styleProps&&npc>0)
dom.setStyles(el,newStyle);else
if(el.nodeName=='SPAN'&&!el.className)
dom.remove(el,true);});}}
if(getParam(ed,"paste_remove_styles")||(getParam(ed,"paste_remove_styles_if_webkit")&&tinymce.isWebKit)){each(dom.select('*[style]',o.node),function(el){el.removeAttribute('style');el.removeAttribute('_mce_style');});}else{if(tinymce.isWebKit){each(dom.select('*',o.node),function(el){el.removeAttribute('_mce_style');});}}},_convertLists:function(pl,o){var dom=pl.editor.dom,listElm,li,lastMargin=-1,margin,levels=[],lastType,html;each(dom.select('p',o.node),function(p){var sib,val='',type,html,idx,parents;for(sib=p.firstChild;sib&&sib.nodeType==3;sib=sib.nextSibling)
val+=sib.nodeValue;val=p.innerHTML.replace(/<\/?\w+[^>]*>/gi,'').replace(/&nbsp;/g,'\u00a0');if(/^(__MCE_ITEM__)+[\u2022\u00b7\u00a7\u00d8o]\s*\u00a0*/.test(val))
type='ul';if(/^__MCE_ITEM__\s*\w+\.\s*\u00a0{2,}/.test(val))
type='ol';if(type){margin=parseFloat(p.style.marginLeft||0);if(margin>lastMargin)
levels.push(margin);if(!listElm||type!=lastType){listElm=dom.create(type);dom.insertAfter(listElm,p);}else{if(margin>lastMargin){listElm=li.appendChild(dom.create(type));}else if(margin<lastMargin){idx=tinymce.inArray(levels,margin);parents=dom.getParents(listElm.parentNode,type);listElm=parents[parents.length-1-idx]||listElm;}}
each(dom.select('span',p),function(span){var html=span.innerHTML.replace(/<\/?\w+[^>]*>/gi,'');if(type=='ul'&&/^[\u2022\u00b7\u00a7\u00d8o]/.test(html))
dom.remove(span);else if(/^[\s\S]*\w+\.(&nbsp;|\u00a0)*\s*/.test(html))
dom.remove(span);});html=p.innerHTML;if(type=='ul')
html=p.innerHTML.replace(/__MCE_ITEM__/g,'').replace(/^[\u2022\u00b7\u00a7\u00d8o]\s*(&nbsp;|\u00a0)+\s*/,'');else
html=p.innerHTML.replace(/__MCE_ITEM__/g,'').replace(/^\s*\w+\.(&nbsp;|\u00a0)+\s*/,'');li=listElm.appendChild(dom.create('li',0,html));dom.remove(p);lastMargin=margin;lastType=type;}else
listElm=lastMargin=0;});html=o.node.innerHTML;if(html.indexOf('__MCE_ITEM__')!=-1)
o.node.innerHTML=html.replace(/__MCE_ITEM__/g,'');},_insertBlockContent:function(ed,dom,content){var parentBlock,marker,sel=ed.selection,last,elm,vp,y,elmHeight,markerId='mce_marker';function select(n){var r;if(tinymce.isIE){r=ed.getDoc().body.createTextRange();r.moveToElementText(n);r.collapse(false);r.select();}else{sel.select(n,1);sel.collapse(false);}}
this._insert('<span id="'+markerId+'">&nbsp;</span>',1);marker=dom.get(markerId);parentBlock=dom.getParent(marker,'p,h1,h2,h3,h4,h5,h6,ul,ol,th,td');if(parentBlock&&!/TD|TH/.test(parentBlock.nodeName)){marker=dom.split(parentBlock,marker);each(dom.create('div',0,content).childNodes,function(n){last=marker.parentNode.insertBefore(n.cloneNode(true),marker);});select(last);}else{dom.setOuterHTML(marker,content);sel.select(ed.getBody(),1);sel.collapse(0);}
while(elm=dom.get(markerId))
dom.remove(elm);elm=sel.getStart();vp=dom.getViewPort(ed.getWin());y=ed.dom.getPos(elm).y;elmHeight=elm.clientHeight;if(y<vp.y||y+elmHeight>vp.y+vp.h)
ed.getDoc().body.scrollTop=y<vp.y?y:y-vp.h+25;},_insert:function(h,skip_undo){var ed=this.editor;if(!ed.selection.isCollapsed())
ed.getDoc().execCommand('Delete',false,null);ed.execCommand(tinymce.isGecko?'insertHTML':'mceInsertContent',false,h,{skip_undo:skip_undo});},_insertPlainText:function(ed,dom,h){var i,len,pos,rpos,node,breakElms,before,after,w=ed.getWin(),d=ed.getDoc(),sel=ed.selection,is=tinymce.is,inArray=tinymce.inArray,linebr=getParam(ed,"paste_text_linebreaktype"),rl=getParam(ed,"paste_text_replacements");function process(items){each(items,function(v){if(v.constructor==RegExp)
h=h.replace(v,"");else
h=h.replace(v[0],v[1]);});};if((typeof(h)==="string")&&(h.length>0)){if(!entities)
entities=("34,quot,38,amp,39,apos,60,lt,62,gt,"+ed.serializer.settings.entities).split(",");if(/<(?:p|br|h[1-6]|ul|ol|dl|table|t[rdh]|div|blockquote|fieldset|pre|address|center)[^>]*>/i.test(h)){process([/[\n\r]+/g]);}else{process([/\r+/g]);}
process([[/<\/(?:p|h[1-6]|ul|ol|dl|table|div|blockquote|fieldset|pre|address|center)>/gi,"\n\n"],[/<br[^>]*>|<\/tr>/gi,"\n"],[/<\/t[dh]>\s*<t[dh][^>]*>/gi,"\t"],/<[a-z!\/?][^>]*>/gi,[/&nbsp;/gi," "],[/&(#\d+|[a-z0-9]{1,10});/gi,function(e,s){if(s.charAt(0)==="#"){return String.fromCharCode(s.slice(1));}
else{return((e=inArray(entities,s))>0)?String.fromCharCode(entities[e-1]):" ";}}],[/(?:(?!\n)\s)*(\n+)(?:(?!\n)\s)*/gi,"$1"],[/\n{3,}/g,"\n\n"],/^\s+|\s+$/g]);h=dom.encode(h);if(!sel.isCollapsed()){d.execCommand("Delete",false,null);}
if(is(rl,"array")||(is(rl,"array"))){process(rl);}
else if(is(rl,"string")){process(new RegExp(rl,"gi"));}
if(linebr=="none"){process([[/\n+/g," "]]);}
else if(linebr=="br"){process([[/\n/g,"<br />"]]);}
else{process([/^\s+|\s+$/g,[/\n\n/g,"</p><p>"],[/\n/g,"<br />"]]);}
if((pos=h.indexOf("</p><p>"))!=-1){rpos=h.lastIndexOf("</p><p>");node=sel.getNode();breakElms=[];do{if(node.nodeType==1){if(node.nodeName=="TD"||node.nodeName=="BODY"){break;}
breakElms[breakElms.length]=node;}}while(node=node.parentNode);if(breakElms.length>0){before=h.substring(0,pos);after="";for(i=0,len=breakElms.length;i<len;i++){before+="</"+breakElms[i].nodeName.toLowerCase()+">";after+="<"+breakElms[breakElms.length-i-1].nodeName.toLowerCase()+">";}
if(pos==rpos){h=before+after+h.substring(pos+7);}
else{h=before+h.substring(pos+4,rpos+4)+after+h.substring(rpos+7);}}}
ed.execCommand("mceInsertRawHTML",false,h+'<span id="_plain_text_marker">&nbsp;</span>');window.setTimeout(function(){var marker=dom.get('_plain_text_marker'),elm,vp,y,elmHeight;sel.select(marker,false);d.execCommand("Delete",false,null);marker=null;elm=sel.getStart();vp=dom.getViewPort(w);y=dom.getPos(elm).y;elmHeight=elm.clientHeight;if((y<vp.y)||(y+elmHeight>vp.y+vp.h)){d.body.scrollTop=y<vp.y?y:y-vp.h+25;}},0);}},_legacySupport:function(){var t=this,ed=t.editor;ed.addCommand("mcePasteWord",function(){ed.windowManager.open({file:t.url+"/pasteword.htm",width:parseInt(getParam(ed,"paste_dialog_width")),height:parseInt(getParam(ed,"paste_dialog_height")),inline:1});});if(getParam(ed,"paste_text_use_dialog")){ed.addCommand("mcePasteText",function(){ed.windowManager.open({file:t.url+"/pastetext.htm",width:parseInt(getParam(ed,"paste_dialog_width")),height:parseInt(getParam(ed,"paste_dialog_height")),inline:1});});}
ed.addButton("pasteword",{title:"paste.paste_word_desc",cmd:"mcePasteWord"});}});tinymce.PluginManager.add("paste",tinymce.plugins.PastePlugin);})();