#! /usr/bin/perl -w
BEGIN {
  unshift @INC, $ENV{FOSWIKICPAN} if defined $ENV{FOSWIKICPAN};
}
use CSS::Minifier qw(minify);

foreach my $file (@ARGV) {
  open(INFILE, $file) or die "failed opening $file";
  my $result = minify(input => *INFILE);
  close(INFILE);
  print "$result\n";
}
