foswiki
foswiki-core
foswiki-configure-cgi
foswiki-apache2
foswiki-system-web-data
foswiki-default-web-data
foswiki-empty-web-data
foswiki-example-data
foswiki-core-autoviewtemplateplugin
foswiki-core-commentplugin
foswiki-core-edittableplugin
foswiki-core-emptyplugin
foswiki-core-famfamfamcontrib
foswiki-core-historyplugin
foswiki-core-interwikiplugin
foswiki-core-jqueryplugin
foswiki-core-preferencesplugin
foswiki-core-renderlistplugin
foswiki-core-slideshowplugin
foswiki-core-smiliesplugin
foswiki-core-spreadsheetplugin
foswiki-core-tableplugin
foswiki-core-tinymceplugin
foswiki-core-twistyplugin
foswiki-core-wysiwygplugin
foswiki-core-twikicompatibilityplugin
foswiki-core-behaviourcontrib
foswiki-core-comparerevisionsaddon
foswiki-core-jscalendarcontrib
foswiki-core-mailercontrib
foswiki-core-patternskin
foswiki-core-tipscontrib
foswiki-core-topicusermappingcontrib
