| twitter | %ICON{twitter}% | twitter |  =%<nop>ICON{twitter}%= |
| stumbleupon | %ICON{stumbleupon}% | stumbleupon |  =%<nop>ICON{stumbleupon}%= |
| digg | %ICON{digg}% | digg |  =%<nop>ICON{digg}%= |
| button-yellow | %ICON{button-yellow}% | button-yellow |  =%<nop>ICON{button-yellow}%= |
| bebo | %ICON{bebo}% | bebo |  =%<nop>ICON{bebo}%= |
| virb | %ICON{virb}% | virb |  =%<nop>ICON{virb}%= |
| mobileme | %ICON{mobileme}% | mobileme |  =%<nop>ICON{mobileme}%= |
| retweet | %ICON{retweet}% | retweet |  =%<nop>ICON{retweet}%= |
| button-red | %ICON{button-red}% | button-red |  =%<nop>ICON{button-red}%= |
| frinedster | %ICON{frinedster}% | frinedster |  =%<nop>ICON{frinedster}%= |
| microsoft | %ICON{microsoft}% | microsoft |  =%<nop>ICON{microsoft}%= |
| vimeo | %ICON{vimeo}% | vimeo |  =%<nop>ICON{vimeo}%= |
| button-white | %ICON{button-white}% | button-white |  =%<nop>ICON{button-white}%= |
| sharethis | %ICON{sharethis}% | sharethis |  =%<nop>ICON{sharethis}%= |
| metacafe | %ICON{metacafe}% | metacafe |  =%<nop>ICON{metacafe}%= |
| slideshare | %ICON{slideshare}% | slideshare |  =%<nop>ICON{slideshare}%= |
| yahoo-buzz | %ICON{yahoo-buzz}% | yahoo-buzz |  =%<nop>ICON{yahoo-buzz}%= |
| ebay | %ICON{ebay}% | ebay |  =%<nop>ICON{ebay}%= |
| facebook | %ICON{facebook}% | facebook |  =%<nop>ICON{facebook}%= |
| mister-wong | %ICON{mister-wong}% | mister-wong |  =%<nop>ICON{mister-wong}%= |
| podcast | %ICON{podcast}% | podcast |  =%<nop>ICON{podcast}%= |
| qik | %ICON{qik}% | qik |  =%<nop>ICON{qik}%= |
| viddler | %ICON{viddler}% | viddler |  =%<nop>ICON{viddler}%= |
| youtube | %ICON{youtube}% | youtube |  =%<nop>ICON{youtube}%= |
| picasa | %ICON{picasa}% | picasa |  =%<nop>ICON{picasa}%= |
| button-green | %ICON{button-green}% | button-green |  =%<nop>ICON{button-green}%= |
| friendfeed | %ICON{friendfeed}% | friendfeed |  =%<nop>ICON{friendfeed}%= |
| aol | %ICON{aol}% | aol |  =%<nop>ICON{aol}%= |
| blogger | %ICON{blogger}% | blogger |  =%<nop>ICON{blogger}%= |
| amazon | %ICON{amazon}% | amazon |  =%<nop>ICON{amazon}%= |
| gowalla | %ICON{gowalla}% | gowalla |  =%<nop>ICON{gowalla}%= |
| button-blue | %ICON{button-blue}% | button-blue |  =%<nop>ICON{button-blue}%= |
| myspace | %ICON{myspace}% | myspace |  =%<nop>ICON{myspace}%= |
| posterous | %ICON{posterous}% | posterous |  =%<nop>ICON{posterous}%= |
| google-buzz | %ICON{google-buzz}% | google-buzz |  =%<nop>ICON{google-buzz}%= |
| xing | %ICON{xing}% | xing |  =%<nop>ICON{xing}%= |
| google | %ICON{google}% | google |  =%<nop>ICON{google}%= |
| wordpress-blue | %ICON{wordpress-blue}% | wordpress-blue |  =%<nop>ICON{wordpress-blue}%= |
| linkedin | %ICON{linkedin}% | linkedin |  =%<nop>ICON{linkedin}%= |
| reddit | %ICON{reddit}% | reddit |  =%<nop>ICON{reddit}%= |
| msn | %ICON{msn}% | msn |  =%<nop>ICON{msn}%= |
| google-talk | %ICON{google-talk}% | google-talk |  =%<nop>ICON{google-talk}%= |
| slashdot | %ICON{slashdot}% | slashdot |  =%<nop>ICON{slashdot}%= |
| paypal | %ICON{paypal}% | paypal |  =%<nop>ICON{paypal}%= |
| drupal | %ICON{drupal}% | drupal |  =%<nop>ICON{drupal}%= |
| icq | %ICON{icq}% | icq |  =%<nop>ICON{icq}%= |
| bing | %ICON{bing}% | bing |  =%<nop>ICON{bing}%= |
| delicious | %ICON{delicious}% | delicious |  =%<nop>ICON{delicious}%= |
| technorati | %ICON{technorati}% | technorati |  =%<nop>ICON{technorati}%= |
| button-light-blue | %ICON{button-light-blue}% | button-light-blue |  =%<nop>ICON{button-light-blue}%= |
| squidoo | %ICON{squidoo}% | squidoo |  =%<nop>ICON{squidoo}%= |
| behance | %ICON{behance}% | behance |  =%<nop>ICON{behance}%= |
| meetup | %ICON{meetup}% | meetup |  =%<nop>ICON{meetup}%= |
| email | %ICON{email}% | email |  =%<nop>ICON{email}%= |
| yelp | %ICON{yelp}% | yelp |  =%<nop>ICON{yelp}%= |
| yahoo | %ICON{yahoo}% | yahoo |  =%<nop>ICON{yahoo}%= |
| feedburner | %ICON{feedburner}% | feedburner |  =%<nop>ICON{feedburner}%= |
| mixx | %ICON{mixx}% | mixx |  =%<nop>ICON{mixx}%= |
| lastfm | %ICON{lastfm}% | lastfm |  =%<nop>ICON{lastfm}%= |
| wordpress | %ICON{wordpress}% | wordpress |  =%<nop>ICON{wordpress}%= |
| star | %ICON{star}% | star |  =%<nop>ICON{star}%= |
| newsvine | %ICON{newsvine}% | newsvine |  =%<nop>ICON{newsvine}%= |
| apple | %ICON{apple}% | apple |  =%<nop>ICON{apple}%= |
| app-store | %ICON{app-store}% | app-store |  =%<nop>ICON{app-store}%= |
| flickr | %ICON{flickr}% | flickr |  =%<nop>ICON{flickr}%= |
| deviant-art | %ICON{deviant-art}% | deviant-art |  =%<nop>ICON{deviant-art}%= |
| button-orange | %ICON{button-orange}% | button-orange |  =%<nop>ICON{button-orange}%= |
| netvibes | %ICON{netvibes}% | netvibes |  =%<nop>ICON{netvibes}%= |
| designfloat | %ICON{designfloat}% | designfloat |  =%<nop>ICON{designfloat}%= |
| tumblr | %ICON{tumblr}% | tumblr |  =%<nop>ICON{tumblr}%= |
| design-bump | %ICON{design-bump}% | design-bump |  =%<nop>ICON{design-bump}%= |
| skype | %ICON{skype}% | skype |  =%<nop>ICON{skype}%= |
