FOSWIKI_ROOT?=~/foswiki/core
TARGET=\
	colors.css \
	column_left.css \
	column_none.css \
	column_right.css \
	column_twiki.css \
	layout.css \
	style.css \
	variant_foswiki.css \
	variant_foswiki_noframe.css \
	variant_twiki.css 

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

clean:
	rm -f $(TARGET) *.gz
