TARGET=\
  jquery.blockUI.css \
  jquery.blockUI.js \
  jquery.blockUI.init.js \
  $(JQUERYPLUGIN_LIB)/BLOCKUI.pm

-include ../../Makefile.include

#git: 
#	git clone https://github.com/malsup/blockui.git $@
#
#ifneq (,$(wildcard git))
#jquery.blockUI.uncompressed.js: git/jquery.blockUI.js
#	cat $^ > $@
#endif
