sh tools/fix_file_permissions.sh
cd ../AutoViewTemplatePlugin && sh ../core/tools/fix_file_permissions.sh
cd ../CompareRevisionsAddOn && sh ../core/tools/fix_file_permissions.sh
cd ../CommentPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../EditRowPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../EmptyPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../FamFamFamContrib && sh ../core/tools/fix_file_permissions.sh
cd ../HistoryPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../HomePagePlugin && sh ../core/tools/fix_file_permissions.sh
cd ../InterwikiPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../JEditableContrib && sh ../core/tools/fix_file_permissions.sh
cd ../JSCalendarContrib && sh ../core/tools/fix_file_permissions.sh
cd ../JQueryPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../MailerContrib && sh ../core/tools/fix_file_permissions.sh
cd ../NatEditPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../PatternSkin && sh ../core/tools/fix_file_permissions.sh
cd ../PlainFileStoreContrib && sh ../core/tools/fix_file_permissions.sh
cd ../PreferencesPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../RCSStoreContrib && sh ../core/tools/fix_file_permissions.sh
cd ../RenderListPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../SlideShowPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../SmiliesPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../SpreadSheetPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../SubscribePlugin && sh ../core/tools/fix_file_permissions.sh
cd ../TablePlugin && sh ../core/tools/fix_file_permissions.sh
cd ../TinyMCEPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../TipsContrib && sh ../core/tools/fix_file_permissions.sh
cd ../TopicUserMappingContrib && sh ../core/tools/fix_file_permissions.sh
cd ../TWikiCompatibilityPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../UpdatesPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../TwistyPlugin && sh ../core/tools/fix_file_permissions.sh
cd ../WysiwygPlugin && sh ../core/tools/fix_file_permissions.sh
