SUBDIRS=plugins
TARGET=\
  noconflict.js \
  jquery-1.9.1.js \
  jquery-1.10.0.js \
  jquery-1.10.1.js \
  jquery-1.11.0.js \
  jquery-1.11.1.js \
  jquery-1.11.2.js \
  jquery-1.11.3.js \
  jquery-1.12.0.js \
  jquery-1.12.1.js \
  jquery-1.12.2.js \
  jquery-1.12.3.js \
  jquery-1.12.4.js \
  jquery-2.0.0.js \
  jquery-2.0.1.js \
  jquery-2.0.2.js \
  jquery-2.1.0.js \
  jquery-2.1.1.js \
  jquery-2.1.3.js \
  jquery-2.2.0.js \
  jquery-2.2.1.js \
  jquery-2.2.2.js \
  jquery-2.2.3.js \
  jquery-2.2.4.js

-include Makefile.include
