SUBDIRS=i18n plugins themes ui
TARGET=\
  jquery-1.4.2.js \
  jquery-1.4.3.js \
  jquery-1.4.4.js \
  jquery-1.5.js \
  jquery-1.5.1.js \
  jquery-1.5.2.js \
  jquery-1.6.1.js \
  jquery-1.6.2.js \
  jquery-1.6.3.js \
  jquery-1.6.4.js \
  jquery-1.7.js \
  jquery-1.7.1.js \

-include Makefile.include
