FOSWIKI_ROOT?=~/foswiki/trunk/core
TARGET= \
  edit.js \
  jquery.natedit.js \
  jquery.natedit.inserttable.js \
  jquery.natedit.insertlink.js \
  jquery.natedit.insertattachment.js \
  styles.css

SUBDIRS=default

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include
