FOSWIKI_ROOT?=~/foswiki/core
TARGET=\
	colors.css \
	column_none.css \
	column_right.css \
	layout.css \
	style.css

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

clean:
	rm -f $(TARGET) *.gz
