TARGET=\
  grid.locale-bg1251.js \
  grid.locale-bg.js \
  grid.locale-cat.js \
  grid.locale-cn.js \
  grid.locale-cs.js \
  grid.locale-de.js \
  grid.locale-dk.js \
  grid.locale-el.js \
  grid.locale-en.js \
  grid.locale-fa.js \
  grid.locale-fi.js \
  grid.locale-fr.js \
  grid.locale-he.js \
  grid.locale-is.js \
  grid.locale-it.js \
  grid.locale-ja.js \
  grid.locale-jp.js \
  grid.locale-nl.js \
  grid.locale-no.js \
  grid.locale-pl.js \
  grid.locale-pt-br.js \
  grid.locale-pt.js \
  grid.locale-ro.js \
  grid.locale-ru.js \
  grid.locale-sp.js \
  grid.locale-sv.js \
  grid.locale-tr.js \
  grid.locale-ua.js

-include ../../../Makefile.include

