/*!
 * jQuery.scrollTo
 * Copyright (c) 2007 Ariel Flesler - aflesler ○ gmail • com | https://github.com/flesler
 * Licensed under MIT
 * https://github.com/flesler/jquery.scrollTo
 * @projectDescription Lightweight, cross-browser and highly customizable animated scrolling with jQuery
 * @author Ariel Flesler
 * @version 2.1.3
 */
!function(e){"use strict";"function"==typeof define&&define.amd?define(["jquery"],e):"undefined"!=typeof module&&module.exports?module.exports=e(require("jquery")):e(jQuery)}(function(e){"use strict";var t=e.scrollTo=function(t,n,o){return e(window).scrollTo(t,n,o)};function n(t){return!t.nodeName||-1!==e.inArray(t.nodeName.toLowerCase(),["iframe","#document","html","body"])}function o(e){return"function"==typeof e}function r(t){return o(t)||e.isPlainObject(t)?t:{top:t,left:t}}return t.defaults={axis:"xy",duration:0,limit:!0},e.fn.scrollTo=function(i,s,u){"object"==typeof s&&(u=s,s=0),"function"==typeof u&&(u={onAfter:u}),"max"===i&&(i=9e9),u=e.extend({},t.defaults,u),s=s||u.duration;var a=u.queue&&u.axis.length>1;return a&&(s/=2),u.offset=r(u.offset),u.over=r(u.over),this.each(function(){if(null!==i){var f,c=n(this),l=c?this.contentWindow||window:this,d=e(l),m=i,p={};switch(typeof m){case"number":case"string":if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(m)){m=r(m);break}m=c?e(m):e(m,l);case"object":if(0===m.length)return;(m.is||m.style)&&(f=(m=e(m)).offset())}var h=o(u.offset)&&u.offset(l,m)||u.offset;e.each(u.axis.split(""),function(e,n){var o="x"===n?"Left":"Top",r=o.toLowerCase(),i="scroll"+o,s=d[i](),v=t.max(l,n);if(f)p[i]=f[r]+(c?0:s-d.offset()[r]),u.margin&&(p[i]-=parseInt(m.css("margin"+o),10)||0,p[i]-=parseInt(m.css("border"+o+"Width"),10)||0),p[i]+=h[r]||0,u.over[r]&&(p[i]+=m["x"===n?"width":"height"]()*u.over[r]);else{var y=m[r];p[i]=y.slice&&"%"===y.slice(-1)?parseFloat(y)/100*v:y}u.limit&&/^\d+$/.test(p[i])&&(p[i]=p[i]<=0?0:Math.min(p[i],v)),!e&&u.axis.length>1&&(s===p[i]?p={}:a&&(x(u.onAfterFirst),p={}))}),x(u.onAfter)}function x(t){var n=e.extend({},u,{queue:!0,duration:s,complete:t&&function(){t.call(l,m,u)}});d.animate(p,n)}})},t.max=function(t,o){var r="x"===o?"Width":"Height",i="scroll"+r;if(!n(t))return t[i]-e(t)[r.toLowerCase()]();var s="client"+r,u=t.ownerDocument||t.document,a=u.documentElement,f=u.body;return Math.max(a[i],f[i])-Math.min(a[s],f[s])},e.Tween.propHooks.scrollLeft=e.Tween.propHooks.scrollTop={get:function(t){return e(t.elem)[t.prop]()},set:function(t){var n=this.get(t);if(t.options.interrupt&&t._last&&t._last!==n)return e(t.elem).stop();var o=Math.round(t.now);n!==o&&(e(t.elem)[t.prop](o),t._last=this.get(t))}},t}),jQuery(function(e){e(document).on("click",".jqScrollToLink",function(){var t=e(this),n=e.extend({},t.data());return e.scrollTo(n.target,n),!1})});
