/*!
 * jQuery.scrollTo
 * Copyright (c) 2007-2015 Ariel Flesler - aflesler ○ gmail • com | http://flesler.blogspot.com
 * Licensed under MIT
 * http://flesler.blogspot.com/2007/10/jqueryscrollto.html
 * @projectDescription Lightweight, cross-browser and highly customizable animated scrolling with jQuery
 * @author Ariel Flesler
 * @version 2.1.2
 */
!function(e){"use strict";"function"==typeof define&&define.amd?define(["jquery"],e):"undefined"!=typeof module&&module.exports?module.exports=e(require("jquery")):e(jQuery)}((function(e){"use strict";var t=e.scrollTo=function(t,n,o){return e(window).scrollTo(t,n,o)};function n(t){return!t.nodeName||-1!==e.inArray(t.nodeName.toLowerCase(),["iframe","#document","html","body"])}function o(t){return e.isFunction(t)||e.isPlainObject(t)?t:{top:t,left:t}}return t.defaults={axis:"xy",duration:0,limit:!0},e.fn.scrollTo=function(r,i,s){"object"==typeof i&&(s=i,i=0),"function"==typeof s&&(s={onAfter:s}),"max"===r&&(r=9e9),s=e.extend({},t.defaults,s),i=i||s.duration;var a=s.queue&&s.axis.length>1;return a&&(i/=2),s.offset=o(s.offset),s.over=o(s.over),this.each((function(){if(null!==r){var u,f=n(this),c=f?this.contentWindow||window:this,l=e(c),d=r,m={};switch(typeof d){case"number":case"string":if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(d)){d=o(d);break}d=f?e(d):e(d,c);case"object":if(0===d.length)return;(d.is||d.style)&&(u=(d=e(d)).offset())}var p=e.isFunction(s.offset)&&s.offset(c,d)||s.offset;e.each(s.axis.split(""),(function(e,n){var o="x"===n?"Left":"Top",r=o.toLowerCase(),i="scroll"+o,x=l[i](),v=t.max(c,n);if(u)m[i]=u[r]+(f?0:x-l.offset()[r]),s.margin&&(m[i]-=parseInt(d.css("margin"+o),10)||0,m[i]-=parseInt(d.css("border"+o+"Width"),10)||0),m[i]+=p[r]||0,s.over[r]&&(m[i]+=d["x"===n?"width":"height"]()*s.over[r]);else{var w=d[r];m[i]=w.slice&&"%"===w.slice(-1)?parseFloat(w)/100*v:w}s.limit&&/^\d+$/.test(m[i])&&(m[i]=m[i]<=0?0:Math.min(m[i],v)),!e&&s.axis.length>1&&(x===m[i]?m={}:a&&(h(s.onAfterFirst),m={}))})),h(s.onAfter)}function h(t){var n=e.extend({},s,{queue:!0,duration:i,complete:t&&function(){t.call(c,d,s)}});l.animate(m,n)}}))},t.max=function(t,o){var r="x"===o?"Width":"Height",i="scroll"+r;if(!n(t))return t[i]-e(t)[r.toLowerCase()]();var s="client"+r,a=t.ownerDocument||t.document,u=a.documentElement,f=a.body;return Math.max(u[i],f[i])-Math.min(u[s],f[s])},e.Tween.propHooks.scrollLeft=e.Tween.propHooks.scrollTop={get:function(t){return e(t.elem)[t.prop]()},set:function(t){var n=this.get(t);if(t.options.interrupt&&t._last&&t._last!==n)return e(t.elem).stop();var o=Math.round(t.now);n!==o&&(e(t.elem)[t.prop](o),t._last=this.get(t))}},t})),jQuery((function(e){e(document).on("click",".jqScrollToLink",(function(){var t=e(this),n=e.extend({},t.data(),t.metadata());return e.scrollTo(n.target,n),!1}))}));
