#!/bin/sh

# POST-COMMIT HOOK
# See post-commit.tmpl for help

REPOS="$1"
REV="$2"

cd $REPOS/hooks

author=`/usr/local/bin/svnlook author -r $REV $REPOS`

# First send out the commit email
./commit-email.pl --from svn@foswiki.org -s "[SVN] $author" "$REPOS" "$REV" foswiki-svn@lists.sourceforge.net
# Then push changes to git, per split repo (global is cron'ed every 15 min)
sudo -u git /home/svn/supportscripts/git-svn-split.pl "$REPOS" "$REV" &
# Tweet about the commit - is this still useful?
/home/svn/supportscripts/twitter.pl
# Update the RSS feed about the subversion history
./rssfeed.sh "$REPOS" "$REV" &
