SUBDIRS=themes
TARGET=\
  jquery-ui.js \
  jquery.ui.spinner.init.js \
  jquery.ui.autocomplete.init.js \
  jquery.ui.resizable.init.js \
  jquery.ui.draggable.init.js \
  jquery.ui.accordion.init.js \
  jquery.ui.tabs.init.js \
  jquery.ui.slider.init.js \
  jquery.ui.dialog.init.js \
  jquery.ui.button.init.js \
  jquery.ui.datepicker.init.js \
  jquery.ui.progressbar.init.js \
  jquery.ui.tooltip.init.js

# TODO: not yet init'ed widgets
# droppable, selectable, sortable

-include ../../Makefile.include
