tinyMCE.addI18n('en.foswikiimage_dlg', {
    dialog_title: "Insert/edit image",
    tab_general: 'General',
    tab_appearance: 'Appearance',
    tab_advanced: 'Advanced',
    general: 'General',
    title: 'Title',
    preview: 'Preview',
    constrain_proportions: 'Constrain proportions',
    langdir: 'Language direction',
    langcode: 'Language code',
    long_desc: 'Long description link',
    style: 'Style',
    classes: 'Classes',
    ltr: 'Left to right',
    rtl: 'Right to left',
    id: 'Id',
    map: 'Image map',
    swap_image: 'Swap image',
    alt_image: 'Alternative image',
    mouseover: 'for mouse over',
    mouseout: 'for mouse out',
    misc: 'Miscellaneous',
    example_img: 'Appearance&nbsp;preview&nbsp;image',
    missing_alt: 'Are you sure you want to continue without including an Image description? Without  it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing with images turned off.',
    img_url_help: 'Enter a full URL, or the simple name of an attachment on this topic. You can use Foswiki macros.',
    src: "Image URL",
    alt: "Image description",
    list: "Image list",
    border: "Border",
    dimensions: "Dimensions",
    vspace: "Vertical space",
    hspace: "Horizontal space",
    align: "Alignment",
    align_baseline: "Baseline",
    align_top: "Top",
    align_middle: "Middle",
    align_bottom: "Bottom",
    align_texttop: "Text top",
    align_textbottom: "Text bottom",
    align_left: "Left",
    align_right: "Right",
    image_list: "Image list"
});